version: 2
orbs:
   heroku: circleci/heroku@x.y
workflows:
   heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: main # only run deploy-via-git job on master branch
jobs:
  build:
    working_directory: ~/acebook-markzuckerbergisalizard
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          PGHOST: localhost
          PGUSER: acebook-markzuckerbergisalizard
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: acebook-markzuckerbergisalizard
          POSTGRES_DB: pgapp_development_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: acebook-markzuckerbergisalizard-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: gem install bundler
      - run: bundle install --path vendor/cache
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: acebook-markzuckerbergisalizard-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the environment
      # - run: cp .sample.env .env
      # Setup the database
      - run: bundle exec rake db:setup
      # Run the tests
      - run: bundle exec rake
