### pre deploy config
version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  heroku_deploy:
    jobs:
      - deploy
jobs:
  build:
    working_directory: ~/acebook-markzuckerbergisalizard
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
        environment:
          PGHOST: localhost
          PGUSER: acebook-markzuckerbergisalizard
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: acebook-markzuckerbergisalizard
          POSTGRES_DB: pgapp_development_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: acebook-markzuckerbergisalizard-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: gem install bundler
      - run: bundle install --path vendor/cache
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: acebook-markzuckerbergisalizard-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Setup the environment
      # - run: cp .sample.env .env
      # Setup the database
      - run: bundle exec rake db:setup
      # Run the tests
      - run: bundle exec rake
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git